// ============================================================
// KHMERRICEHUB — DEMO DATA
// Shapes mirror the Cloud Firestore collections the app will use:
//   riceListings, farmers, users, orders, messages, notifications,
//   reviews, categories
// ============================================================

import farmerHarvest from "../assets/farmers/farmer-harvest.jpg";
import farmerHarvesting from "../assets/farmers/farmer-harvesting.jpg";
import farmerPortrait from "../assets/farmers/farmer-portrait.jpg";
import farmerRaking from "../assets/farmers/farmer-raking.jpg";
import farmerSeedlings from "../assets/farmers/farmer-seedlings.jpg";
import farmerSilhouette from "../assets/farmers/farmer-silhouette.jpg";
import farmerSunset from "../assets/farmers/farmer-sunset.jpg";
import farmerWomanRice from "../assets/farmers/farmer-woman-rice.jpg";

export const FARMER_IMAGES = [
  farmerHarvest,
  farmerHarvesting,
  farmerPortrait,
  farmerRaking,
  farmerSeedlings,
  farmerSilhouette,
  farmerSunset,
  farmerWomanRice,
];

export const RICE_IMAGES = [
  "https://images.unsplash.com/photo-1586208958839-06c17cacdf08?auto=format&fit=crop&w=1000&q=80",
  "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=1000&q=80",
  "https://images.unsplash.com/photo-1532336414038-cf19250c5757?auto=format&fit=crop&w=1000&q=80",
  "https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=1000&q=80",
  "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1000&q=80",
  "https://images.unsplash.com/photo-1695708429374-8b78156fad3e?auto=format&fit=crop&w=1000&q=80",
  "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=1000&q=80",
  "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1000&q=80",
];

export const HERO_IMAGE =
  "https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=1800&q=85";

export const PROVINCES = [
  "Battambang",
  "Kampong Thom",
  "Takeo",
  "Siem Reap",
  "Prey Veng",
  "Kampot",
  "Pursat",
  "Kandal",
];

export const RICE_TYPES = [
  "Fragrant Rice",
  "Jasmine Rice",
  "Organic Rice",
  "White Rice",
  "Glutinous Rice",
  "Red Rice",
  "Specialty Rice",
];

export const CATEGORIES = [
  { id: "fragrant", name: "Fragrant Rice", slug: "fragrant-rice", count: 42, color: "#2e7d32" },
  { id: "jasmine", name: "Jasmine Rice", slug: "jasmine-rice", count: 38, color: "#43a047" },
  { id: "organic", name: "Organic Rice", slug: "organic-rice", count: 27, color: "#22c55e" },
  { id: "white", name: "White Rice", slug: "white-rice", count: 33, color: "#f9a825" },
  { id: "glutinous", name: "Glutinous Rice", slug: "glutinous-rice", count: 19, color: "#2563eb" },
  { id: "red", name: "Red Rice", slug: "red-rice", count: 14, color: "#dc2626" },
  { id: "specialty", name: "Specialty Rice", slug: "specialty-rice", count: 11, color: "#7c3aed" },
];

export const FARMERS = [
  {
    id: "f1",
    name: "Sokha Farm",
    owner: "Sokha Chea",
    province: "Battambang",
    district: "Banan",
    rating: 4.9,
    reviews: 214,
    products: 12,
    followers: 1280,
    verified: true,
    bio: "Family-owned farm growing fragrant jasmine rice in the Battambang plains since 1998.",
    completedProfile: 100,
  },
  {
    id: "f2",
    name: "Green Fields Co.",
    owner: "Rithy Chheang",
    province: "Kampong Thom",
    district: "Stoung",
    rating: 4.8,
    reviews: 176,
    products: 9,
    followers: 940,
    verified: true,
    bio: "Certified organic producer focused on sustainable lowland rice varieties.",
    completedProfile: 92,
  },
  {
    id: "f3",
    name: "Maly Harvest",
    owner: "Maly Sorn",
    province: "Takeo",
    district: "Tram Kak",
    rating: 4.9,
    reviews: 158,
    products: 7,
    followers: 810,
    verified: true,
    bio: "A women-led cooperative famous for heritage red and glutinous rice.",
    completedProfile: 100,
  },
  {
    id: "f4",
    name: "Battambang Rice Co.",
    owner: "Dara Kong",
    province: "Battambang",
    district: "Ratanak Mondol",
    rating: 4.7,
    reviews: 132,
    products: 15,
    followers: 1120,
    verified: true,
    bio: "Large-scale exporter of premium long-grain rice to regional markets.",
    completedProfile: 85,
  },
  {
    id: "f5",
    name: "Prey Veng Fields",
    owner: "Chan Thea",
    province: "Prey Veng",
    district: "Sithor Kandal",
    rating: 4.6,
    reviews: 98,
    products: 6,
    followers: 540,
    verified: false,
    bio: "Smallholder farmer growing organic white rice with natural irrigation.",
    completedProfile: 70,
  },
  {
    id: "f6",
    name: "Siem Reap Rice Co-op",
    owner: "Srey Neang",
    province: "Siem Reap",
    district: "Puok",
    rating: 4.8,
    reviews: 143,
    products: 8,
    followers: 760,
    verified: true,
    bio: "Co-operative of 40 farmers preserving traditional jasmine varieties.",
    completedProfile: 95,
  },
];

export const RICE_LISTINGS = [
  {
    id: "r1",
    name: "Premium Jasmine Rice",
    type: "Jasmine Rice",
    category: "fragrant",
    province: "Battambang",
    district: "Banan",
    price: 1.25,
    quantity: 2500,
    unit: "kg",
    farmerId: "f1",
    farmer: "Sokha Farm",
    rating: 4.9,
    reviews: 214,
    organic: false,
    status: "Published",
    featured: true,
    stock: 84,
    description:
      "Aromatic long-grain jasmine rice harvested from a single 2026 season crop. Naturally fragrant with a soft, fluffy texture — perfect for daily meals and special occasions.",
    specs: {
      "Harvest season": "2026 (rainy season)",
      "Grain length": "7.1 mm",
      "Moisture": "13.5%",
      "Purity": "95%",
      "Packaging": "50 kg sacks",
      "GMO": "No",
    },
    image: farmerHarvest,
    gallery: [farmerHarvest, farmerWomanRice, RICE_IMAGES[0], farmerRaking],
  },
  {
    id: "r2",
    name: "Organic White Rice",
    type: "Organic Rice",
    category: "organic",
    province: "Kampong Thom",
    district: "Stoung",
    price: 1.1,
    quantity: 1800,
    unit: "kg",
    farmerId: "f2",
    farmer: "Green Fields Co.",
    rating: 4.8,
    reviews: 176,
    organic: true,
    status: "Published",
    featured: true,
    stock: 92,
    description:
      "Certified organic white rice grown without chemical fertilizers or pesticides. Clean, mild taste and reliable cooking performance for restaurants and households.",
    specs: {
      "Harvest season": "2026 (wet season)",
      "Grain length": "6.5 mm",
      "Moisture": "12.8%",
      "Purity": "98%",
      "Certification": "Organic, USDA",
      "Packaging": "25 kg sacks",
    },
    image: farmerSeedlings,
    gallery: [farmerSeedlings, farmerPortrait, RICE_IMAGES[1]],
  },
  {
    id: "r3",
    name: "Heritage Red Rice",
    type: "Red Rice",
    category: "red",
    province: "Takeo",
    district: "Tram Kak",
    price: 1.45,
    quantity: 950,
    unit: "kg",
    farmerId: "f3",
    farmer: "Maly Harvest",
    rating: 4.9,
    reviews: 158,
    organic: true,
    status: "Published",
    featured: true,
    stock: 61,
    description:
      "Traditional Cambodian red rice rich in fiber and antioxidants. A nutty, chewy grain prized by health-conscious buyers and specialty restaurants.",
    specs: {
      "Harvest season": "2025 (dry season)",
      "Grain length": "6.8 mm",
      "Moisture": "12.5%",
      "Purity": "97%",
      "Certification": "Organic",
      "Packaging": "25 kg sacks",
    },
    image: farmerSunset,
    gallery: [farmerSunset, farmerHarvesting, RICE_IMAGES[2]],
  },
  {
    id: "r4",
    name: "Phka Rumduol Fragrant Rice",
    type: "Fragrant Rice",
    category: "fragrant",
    province: "Battambang",
    district: "Ratanak Mondol",
    price: 1.35,
    quantity: 4200,
    unit: "kg",
    farmerId: "f4",
    farmer: "Battambang Rice Co.",
    rating: 4.7,
    reviews: 132,
    organic: false,
    status: "Published",
    featured: false,
    stock: 78,
    description:
      "The celebrated Phka Rumduol variety — Cambodia's award-winning fragrant rice. Long grain, intensely aromatic, and ideal for export-grade packaging.",
    specs: {
      "Harvest season": "2026 (rainy season)",
      "Grain length": "7.0 mm",
      "Moisture": "13.2%",
      "Purity": "96%",
      "Award": "World's Best Rice 2022",
      "Packaging": "50 kg sacks",
    },
    image: RICE_IMAGES[6],
    gallery: [RICE_IMAGES[6], RICE_IMAGES[0], RICE_IMAGES[3]],
  },
  {
    id: "r5",
    name: "Natural White Rice",
    type: "White Rice",
    category: "white",
    province: "Prey Veng",
    district: "Sithor Kandal",
    price: 0.95,
    quantity: 1100,
    unit: "kg",
    farmerId: "f5",
    farmer: "Prey Veng Fields",
    rating: 4.6,
    reviews: 98,
    organic: true,
    status: "Published",
    featured: false,
    stock: 55,
    description:
      "Affordable everyday white rice grown with natural irrigation. Consistent quality at a budget-friendly price for local households and shops.",
    specs: {
      "Harvest season": "2026 (wet season)",
      "Grain length": "6.2 mm",
      "Moisture": "13.0%",
      "Purity": "94%",
      "Packaging": "10 / 25 kg sacks",
    },
    image: RICE_IMAGES[4],
    gallery: [RICE_IMAGES[4], RICE_IMAGES[1]],
  },
  {
    id: "r6",
    name: "Traditional Glutinous Rice",
    type: "Glutinous Rice",
    category: "glutinous",
    province: "Siem Reap",
    district: "Puok",
    price: 1.15,
    quantity: 1400,
    unit: "kg",
    farmerId: "f6",
    farmer: "Siem Reap Rice Co-op",
    rating: 4.8,
    reviews: 143,
    organic: false,
    status: "Published",
    featured: false,
    stock: 71,
    description:
      "Sticky, sweet glutinous rice from the co-op's 40 member farms. A staple for traditional Khmer desserts and ceremonial cooking.",
    specs: {
      "Harvest season": "2026 (rainy season)",
      "Grain length": "6.6 mm",
      "Moisture": "12.9%",
      "Purity": "95%",
      "Packaging": "50 kg sacks",
    },
    image: RICE_IMAGES[5],
    gallery: [RICE_IMAGES[5], RICE_IMAGES[7], RICE_IMAGES[2]],
  },
  {
    id: "r7",
    name: "Fragrant Rice (Mill Grade A)",
    type: "Fragrant Rice",
    category: "fragrant",
    province: "Kampot",
    district: "Tuek Chhou",
    price: 1.2,
    quantity: 3000,
    unit: "kg",
    farmerId: "f1",
    farmer: "Sokha Farm",
    rating: 4.8,
    reviews: 121,
    organic: false,
    status: "Draft",
    featured: false,
    stock: 40,
    description: "High-grade fragrant rice for bulk buyers. Sample available on request.",
    specs: {
      "Harvest season": "2026",
      "Grain length": "6.9 mm",
      "Moisture": "13.4%",
      "Packaging": "50 kg sacks",
    },
    image: RICE_IMAGES[7],
    gallery: [RICE_IMAGES[7], RICE_IMAGES[0]],
  },
  {
    id: "r8",
    name: "Organic Jasmine (Small Batch)",
    type: "Jasmine Rice",
    category: "organic",
    province: "Pursat",
    district: "Kandieng",
    price: 1.5,
    quantity: 600,
    unit: "kg",
    farmerId: "f3",
    farmer: "Maly Harvest",
    rating: 4.9,
    reviews: 87,
    organic: true,
    status: "Published",
    featured: false,
    stock: 33,
    description:
      "Limited small-batch organic jasmine. Deep aroma, high shine after cooking, and fully traceable to one field.",
    specs: {
      "Harvest season": "2026 (dry season)",
      "Grain length": "7.1 mm",
      "Moisture": "12.6%",
      "Certification": "Organic, EU",
      "Packaging": "5 / 25 kg sacks",
    },
    image: RICE_IMAGES[3],
    gallery: [RICE_IMAGES[3], RICE_IMAGES[5], RICE_IMAGES[1]],
  },
  {
    id: "r9",
    name: "White Rice 5% Broken",
    type: "White Rice",
    category: "white",
    province: "Kandal",
    district: "Koh Thom",
    price: 0.9,
    quantity: 5200,
    unit: "kg",
    farmerId: "f4",
    farmer: "Battambang Rice Co.",
    rating: 4.5,
    reviews: 76,
    organic: false,
    status: "Published",
    featured: false,
    stock: 95,
    description:
      "Commercial white rice with 5% broken grains. Reliable bulk supply for restaurants, caterers, and wholesalers.",
    specs: {
      "Harvest season": "2026",
      "Grain length": "6.3 mm",
      "Moisture": "13.0%",
      "Broken": "5% max",
      "Packaging": "50 kg sacks",
    },
    image: RICE_IMAGES[6],
    gallery: [RICE_IMAGES[6], RICE_IMAGES[4]],
  },
  {
    id: "r10",
    name: "Red Cargo Rice",
    type: "Red Rice",
    category: "red",
    province: "Kampot",
    district: "Angkor Chey",
    price: 1.4,
    quantity: 780,
    unit: "kg",
    farmerId: "f6",
    farmer: "Siem Reap Rice Co-op",
    rating: 4.7,
    reviews: 64,
    organic: false,
    status: "Published",
    featured: false,
    stock: 48,
    description: "Partially-milled red cargo rice that keeps its nutrient-rich bran layer.",
    specs: {
      "Harvest season": "2025",
      "Grain length": "6.7 mm",
      "Moisture": "12.7%",
      "Packaging": "25 kg sacks",
    },
    image: RICE_IMAGES[2],
    gallery: [RICE_IMAGES[2], RICE_IMAGES[7]],
  },
  {
    id: "r11",
    name: "Black Glutinous Rice",
    type: "Glutinous Rice",
    category: "specialty",
    province: "Battambang",
    district: "Banan",
    price: 1.6,
    quantity: 420,
    unit: "kg",
    farmerId: "f3",
    farmer: "Maly Harvest",
    rating: 4.8,
    reviews: 52,
    organic: true,
    status: "Draft",
    featured: false,
    stock: 20,
    description: "Rare black glutinous rice used for purple rice porridge and desserts.",
    specs: {
      "Harvest season": "2026",
      "Grain length": "6.4 mm",
      "Moisture": "12.4%",
      "Certification": "Organic",
      "Packaging": "5 / 10 kg sacks",
    },
    image: RICE_IMAGES[5],
    gallery: [RICE_IMAGES[5], RICE_IMAGES[2]],
  },
  {
    id: "r12",
    name: "Jasmine Rice (Export Grade)",
    type: "Jasmine Rice",
    category: "jasmine",
    province: "Prey Veng",
    district: "Kamchay Mear",
    price: 1.3,
    quantity: 3600,
    unit: "kg",
    farmerId: "f2",
    farmer: "Green Fields Co.",
    rating: 4.8,
    reviews: 109,
    organic: false,
    status: "Published",
    featured: false,
    stock: 88,
    description: "Export-grade jasmine rice, fully traceable, ready for container shipment.",
    specs: {
      "Harvest season": "2026 (rainy season)",
      "Grain length": "7.0 mm",
      "Moisture": "13.1%",
      "Purity": "97%",
      "Packaging": "Custom / 50 kg",
    },
    image: RICE_IMAGES[1],
    gallery: [RICE_IMAGES[1], RICE_IMAGES[3], RICE_IMAGES[0]],
  },
];

export const REVIEWS = [
  {
    id: "rev1",
    name: "Dara S.",
    role: "Home cook, Phnom Penh",
    rating: 5,
    date: "2026-07-22",
    text: "The jasmine rice is exceptional — fragrant, clean, and consistently fluffy. Knowing exactly which farm it came from makes all the difference.",
  },
  {
    id: "rev2",
    name: "Chenda R.",
    role: "Restaurant owner, Siem Reap",
    rating: 5,
    date: "2026-07-18",
    text: "We buy the organic white rice in bulk every month. Quality has been stable and delivery is always on time.",
  },
  {
    id: "rev3",
    name: "Sopheak L.",
    role: "Export buyer",
    rating: 4,
    date: "2026-07-10",
    text: "Great communication with the farmer and proper documentation. Deducted one star only because the grain length varied slightly between sacks.",
  },
  {
    id: "rev4",
    name: "Nita V.",
    role: "Home cook, Kandal",
    rating: 5,
    date: "2026-07-02",
    text: "Beautiful red rice! Cooks up chewy and nutty. My family loves it and the price is fair.",
  },
];

export const ORDERS = [
  {
    id: "KRH-1042",
    date: "2026-07-28",
    status: "Delivered",
    items: [
      { listingId: "r1", name: "Premium Jasmine Rice", qty: 100, unitPrice: 1.25 },
      { listingId: "r3", name: "Heritage Red Rice", qty: 50, unitPrice: 1.45 },
    ],
    total: 197.5,
    payment: "Paid",
    tracking: [
      { label: "Order placed", date: "2026-07-28", done: true },
      { label: "Confirmed by farmer", date: "2026-07-28", done: true },
      { label: "In transit", date: "2026-07-30", done: true },
      { label: "Delivered", date: "2026-08-01", done: true },
    ],
  },
  {
    id: "KRH-1029",
    date: "2026-07-15",
    status: "Shipped",
    items: [{ listingId: "r8", name: "Organic Jasmine (Small Batch)", qty: 25, unitPrice: 1.5 }],
    total: 37.5,
    payment: "Paid",
    tracking: [
      { label: "Order placed", date: "2026-07-15", done: true },
      { label: "Confirmed by farmer", date: "2026-07-16", done: true },
      { label: "In transit", date: "2026-07-31", done: true },
      { label: "Delivered", date: null, done: false },
    ],
  },
  {
    id: "KRH-1015",
    date: "2026-06-20",
    status: "Processing",
    items: [{ listingId: "r6", name: "Traditional Glutinous Rice", qty: 40, unitPrice: 1.15 }],
    total: 46,
    payment: "Paid",
    tracking: [
      { label: "Order placed", date: "2026-06-20", done: true },
      { label: "Confirmed by farmer", date: "2026-06-20", done: true },
      { label: "In transit", date: null, done: false },
      { label: "Delivered", date: null, done: false },
    ],
  },
  {
    id: "KRH-1009",
    date: "2026-05-30",
    status: "Completed",
    items: [{ listingId: "r5", name: "Natural White Rice", qty: 200, unitPrice: 0.95 }],
    total: 190,
    payment: "Paid",
    tracking: [
      { label: "Order placed", date: "2026-05-30", done: true },
      { label: "Confirmed by farmer", date: "2026-05-31", done: true },
      { label: "In transit", date: "2026-06-02", done: true },
      { label: "Delivered", date: "2026-06-05", done: true },
    ],
  },
];

export const NOTIFICATIONS = [
  { id: "n1", type: "Order", title: "Order KRH-1042 delivered", body: "Your jasmine rice from Sokha Farm has arrived.", time: "2026-08-01T09:00:00", read: false },
  { id: "n2", type: "Message", title: "New message from Sokha Farm", body: "Sokha replied about bulk pricing for your order.", time: "2026-07-31T14:20:00", read: false },
  { id: "n3", type: "System", title: "Payment confirmed", body: "Your payment of $197.50 was received.", time: "2026-07-28T11:05:00", read: true },
  { id: "n4", type: "Order", title: "Order KRH-1029 is in transit", body: "Your organic jasmine rice left Battambang.", time: "2026-07-31T08:00:00", read: false },
  { id: "n5", type: "System", title: "Welcome to KhmerRiceHub", body: "Complete your profile to unlock ordering.", time: "2026-07-01T10:00:00", read: true },
];

export const MESSAGES = [
  {
    id: "m1",
    with: { id: "f1", name: "Sokha Farm", province: "Battambang", online: true },
    unread: 2,
    last: "Yes, we can do 2,000 kg at $1.20/kg.",
    time: "2026-08-01T09:12:00",
    messages: [
      { from: "me", text: "Hello! Is the jasmine rice still available for this month?", time: "2026-07-31T14:00:00" },
      { from: "them", text: "Hi! Yes, we have ~2,500 kg left from the rainy season crop.", time: "2026-07-31T14:05:00" },
      { from: "me", text: "What price could you do for 2,000 kg?", time: "2026-07-31T14:10:00" },
      { from: "them", text: "Yes, we can do 2,000 kg at $1.20/kg.", time: "2026-08-01T09:12:00" },
    ],
  },
  {
    id: "m2",
    with: { id: "f3", name: "Maly Harvest", province: "Takeo", online: false },
    unread: 0,
    last: "We shipped the red rice samples this morning.",
    time: "2026-07-30T16:40:00",
    messages: [
      { from: "me", text: "Hi Maly, can you send a sample of the red rice?", time: "2026-07-29T10:00:00" },
      { from: "them", text: "Of course! Which region should I address it to?", time: "2026-07-29T10:30:00" },
      { from: "them", text: "We shipped the red rice samples this morning.", time: "2026-07-30T16:40:00" },
    ],
  },
  {
    id: "m3",
    with: { id: "f4", name: "Battambang Rice Co.", province: "Battambang", online: true },
    unread: 0,
    last: "Please share the specs for your container order.",
    time: "2026-07-28T09:00:00",
    messages: [
      { from: "them", text: "Please share the specs for your container order.", time: "2026-07-28T09:00:00" },
    ],
  },
];

export const STATS = {
  farmers: 1248,
  buyers: 8573,
  listings: 3421,
  provinces: 24,
  satisfaction: 98,
  monthlyOrders: 1864,
  monthlyRevenue: 212400,
};

export const PLATFORM_STATS = [
  { value: "1,200+", label: "Verified farmers" },
  { value: "8,500+", label: "Happy buyers" },
  { value: "24", label: "Provinces reached" },
  { value: "98%", label: "Quality satisfaction" },
];

export const PARTNERS = [
  "MAFF Cambodia",
  "AMRU Rice",
  "ACLEDA Bank",
  "Cambodia Post",
  "Bakong Bakery",
  "CRF Cambodia",
];

export const TESTIMONIALS = [
  {
    id: "t1",
    text: "I found a reliable farmer and the jasmine rice is exceptional. It feels good knowing exactly where it comes from.",
    name: "Dara S.",
    role: "Home cook, Phnom Penh",
    initials: "DS",
    rating: 5,
  },
  {
    id: "t2",
    text: "KhmerRiceHub helped us connect with buyers beyond our province. It has changed how we sell our harvest.",
    name: "Chenda R.",
    role: "Rice farmer, Battambang",
    initials: "CR",
    rating: 5,
  },
  {
    id: "t3",
    text: "The platform is simple, transparent, and the quality of every order has been excellent.",
    name: "Sopheak L.",
    role: "Restaurant owner, Siem Reap",
    initials: "SL",
    rating: 5,
  },
  {
    id: "t4",
    text: "Bulk export purchasing has never been this easy. Traceability and documents are handled properly.",
    name: "Nara K.",
    role: "Export buyer",
    initials: "NK",
    rating: 5,
  },
];

export const TIMELINE = [
  { year: "2018", title: "The idea begins", text: "Founders travel Cambodia's rice belt and meet farmers struggling to reach buyers beyond local markets." },
  { year: "2019", title: "Pilot in Battambang", text: "First 40 farmers list their harvests on a simple directory shared with Phnom Penh restaurants." },
  { year: "2021", title: "Marketplace launch", text: "Secure messaging, verified farmers, and payments bring the marketplace to life across 8 provinces." },
  { year: "2023", title: "Export readiness", text: "Bulk-order tools, documentation, and logistics partnerships open the door for export buyers." },
  { year: "2026", title: "24 provinces strong", text: "1,200+ farmers and 8,500+ buyers trade rice worth over $2.5M annually." },
];

export const TEAM = [
  { name: "Vannak Chan", role: "Co-founder & CEO", initials: "VC", province: "Phnom Penh" },
  { name: "Lyna Kim", role: "Co-founder & CTO", initials: "LK", province: "Phnom Penh" },
  { name: "Sothea Nhim", role: "Head of Operations", initials: "SN", province: "Battambang" },
  { name: "Ratana Pov", role: "Community Lead", initials: "RP", province: "Siem Reap" },
];

export const FAQS = [
  { id: "q1", category: "General", question: "What is KhmerRiceHub?", answer: "KhmerRiceHub is Cambodia's online marketplace connecting rice farmers directly with buyers — from households to exporters. Farmers list their harvest, and buyers browse, compare, and purchase with full transparency about origin and quality." },
  { id: "q2", category: "General", question: "Is KhmerRiceHub free to use?", answer: "Creating an account, browsing listings, and messaging farmers is free. We charge a small service fee on completed orders to keep the platform running, and offer optional promoted listings for farmers." },
  { id: "q3", category: "Buying", question: "How do I verify the quality of the rice?", answer: "Every listing includes harvest details, grain specifications, and photos. Verified farmers have completed identity checks, and buyers can request samples before placing a bulk order." },
  { id: "q4", category: "Buying", question: "What payment methods are supported?", answer: "We support cash on delivery, bank transfer via ACLEDA and ABA, and major cards. Payment happens securely through our checkout flow with clear receipts." },
  { id: "q5", category: "Buying", question: "How is delivery handled?", answer: "Farmers arrange delivery through our partner logistics (Cambodia Post and regional carriers). You'll see live tracking updates from the farm to your door." },
  { id: "q6", category: "Selling", question: "How do I start selling as a farmer?", answer: "Create a farmer account, complete your profile verification, and publish your first listing. We provide guidance, market insights, and support throughout." },
  { id: "q7", category: "Selling", question: "When do farmers get paid?", answer: "Payouts are released within 3 business days of a confirmed delivery. You can track earnings in your farmer dashboard." },
  { id: "q8", category: "Selling", question: "Can I sell in bulk or export?", answer: "Yes. Export buyers can place bulk orders with proper documentation. Our team assists with paperwork and logistics for container shipments." },
];

export const NAV_ITEMS = [
  { label: "Marketplace", to: "/marketplace" },
  { label: "About", to: "/about" },
  { label: "Contact", to: "/contact" },
  { label: "FAQ", to: "/faq" },
];

// Chart data — monthly series
export const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
export const REVENUE_SERIES = [18, 24, 22, 31, 28, 36, 42, 48, 44, 52, 58, 66];
export const ORDERS_SERIES = [140, 190, 172, 240, 218, 290, 335, 380, 350, 420, 470, 520];
export const VISITORS_SERIES = [820, 940, 890, 1180, 1100, 1360, 1520, 1710, 1580, 1880, 2050, 2280];

export const SALES_BY_CATEGORY = [
  { label: "Jasmine", value: 34, color: "#2e7d32" },
  { label: "Fragrant", value: 26, color: "#43a047" },
  { label: "Organic", value: 17, color: "#22c55e" },
  { label: "White", value: 12, color: "#f9a825" },
  { label: "Glutinous", value: 7, color: "#2563eb" },
  { label: "Red / Other", value: 4, color: "#dc2626" },
];

export const TRAFFIC_SOURCES = [
  { label: "Direct", value: 42, color: "#2e7d32" },
  { label: "Organic search", value: 28, color: "#43a047" },
  { label: "Social", value: 17, color: "#f9a825" },
  { label: "Referral", value: 13, color: "#2563eb" },
];

export const USER_BREAKDOWN = [
  { label: "Buyers", value: 72, color: "#2e7d32" },
  { label: "Farmers", value: 24, color: "#f9a825" },
  { label: "Admins", value: 4, color: "#2563eb" },
];

export const TOP_PRODUCTS = [
  { id: "r1", name: "Premium Jasmine Rice", sold: 1240, revenue: 1550, trend: 18 },
  { id: "r4", name: "Phka Rumduol Fragrant Rice", sold: 980, revenue: 1323, trend: 12 },
  { id: "r3", name: "Heritage Red Rice", sold: 640, revenue: 928, trend: 9 },
  { id: "r2", name: "Organic White Rice", sold: 580, revenue: 638, trend: 6 },
];

export const RECENT_ACTIVITIES = [
  { id: "a1", type: "user", text: "New buyer account registered", meta: "Nita V. · Phnom Penh", time: "2026-08-01T10:22:00" },
  { id: "a2", type: "farmer", text: "Farmer verification requested", meta: "Prey Veng Fields", time: "2026-08-01T09:40:00" },
  { id: "a3", type: "product", text: "New listing submitted for review", meta: "Black Glutinous Rice", time: "2026-08-01T08:15:00" },
  { id: "a4", type: "order", text: "Order KRH-1042 delivered", meta: "$197.50 · Sokha Farm", time: "2026-08-01T07:58:00" },
  { id: "a5", type: "payment", text: "Payout sent to farmer", meta: "Siem Reap Rice Co-op · $1,240", time: "2026-07-31T17:00:00" },
  { id: "a6", type: "report", text: "Report resolved", meta: "Listing content flagged", time: "2026-07-31T15:30:00" },
];

export const ADMIN_USERS = [
  { id: "u1", name: "Sokha Chea", email: "sokha@sokhafarm.com", role: "Farmer", status: "Verified", province: "Battambang", joined: "2025-03-12", orders: 48 },
  { id: "u2", name: "Nita Vira", email: "nita.v@email.com", role: "Buyer", status: "Verified", province: "Phnom Penh", joined: "2025-11-02", orders: 17 },
  { id: "u3", name: "Rithy Chheang", email: "rithy@greenfields.co", role: "Farmer", status: "Verified", province: "Kampong Thom", joined: "2025-05-21", orders: 36 },
  { id: "u4", name: "Dara Kong", email: "dara@btrice.com", role: "Farmer", status: "Verified", province: "Battambang", joined: "2025-01-09", orders: 64 },
  { id: "u5", name: "Srey Neang", email: "srey@coop.kh", role: "Farmer", status: "Pending", province: "Siem Reap", joined: "2026-07-19", orders: 0 },
  { id: "u6", name: "Kimheng Pen", email: "kimheng@email.com", role: "Buyer", status: "Suspended", province: "Kandal", joined: "2025-09-30", orders: 3 },
  { id: "u7", name: "Vannak Chan", email: "vannak@khmerricehub.com", role: "Admin", status: "Verified", province: "Phnom Penh", joined: "2024-01-01", orders: 0 },
  { id: "u8", name: "Maly Sorn", email: "maly@malyharvest.com", role: "Farmer", status: "Verified", province: "Takeo", joined: "2025-02-14", orders: 52 },
];

export const PENDING_FARMERS = [
  {
    id: "pf1",
    name: "Prey Veng Fields",
    owner: "Chan Thea",
    province: "Prey Veng",
    joined: "2026-07-25",
    documents: ["National ID", "Farm land certificate", "Bank account"],
    products: 6,
    notes: "Wants to list organic white rice. References available from local co-op.",
    status: "Pending",
  },
  {
    id: "pf2",
    name: "Siem Reap Rice Co-op",
    owner: "Srey Neang",
    province: "Siem Reap",
    joined: "2026-07-19",
    documents: ["Co-op registration", "Farm land certificate", "Bank account"],
    products: 8,
    notes: "Co-operative of 40 farmers. Seeking export partnerships.",
    status: "Pending",
  },
  {
    id: "pf3",
    name: "Kampot Highlands Farm",
    owner: "Bora Meas",
    province: "Kampot",
    joined: "2026-07-28",
    documents: ["National ID", "Farm land certificate"],
    products: 3,
    notes: "National ID scan is slightly low-resolution; flagged for re-submission.",
    status: "More Info",
  },
];

export const PENDING_PRODUCTS = [
  {
    id: "pp1",
    name: "Black Glutinous Rice",
    farmer: "Maly Harvest",
    province: "Battambang",
    price: 1.6,
    submitted: "2026-08-01",
    status: "Pending",
    image: RICE_IMAGES[5],
    flags: [],
  },
  {
    id: "pp2",
    name: "Fragrant Rice (Mill Grade A)",
    farmer: "Sokha Farm",
    province: "Kampot",
    price: 1.2,
    submitted: "2026-07-30",
    status: "Pending",
    image: RICE_IMAGES[7],
    flags: [],
  },
  {
    id: "pp3",
    name: "Yellow Premium Rice",
    farmer: "Unverified Account",
    province: "Unknown",
    price: 0.5,
    submitted: "2026-07-29",
    status: "Flagged",
    image: RICE_IMAGES[2],
    flags: ["Suspicious price", "Unverified seller"],
  },
];

export const NAV_BUYER = [
  { to: "/buyer/dashboard", label: "Overview", icon: "LayoutDashboard" },
  { to: "/buyer/orders", label: "Orders", icon: "ShoppingBag" },
  { to: "/buyer/favorites", label: "Favorites", icon: "Heart" },
  { to: "/buyer/messages", label: "Messages", icon: "MessageSquare", badge: 2 },
  { to: "/buyer/notifications", label: "Notifications", icon: "Bell", badge: 3 },
  { to: "/buyer/profile", label: "My Profile", icon: "User" },
];

export const NAV_FARMER = [
  { to: "/farmer/dashboard", label: "Overview", icon: "LayoutDashboard" },
  { to: "/farmer/listings", label: "Manage Listings", icon: "Wheat" },
  { to: "/farmer/listings/add", label: "Add Listing", icon: "PlusCircle" },
  { to: "/farmer/orders", label: "Orders", icon: "ShoppingBag", badge: 4 },
  { to: "/farmer/messages", label: "Messages", icon: "MessageSquare", badge: 2 },
  { to: "/farmer/notifications", label: "Notifications", icon: "Bell" },
  { to: "/farmer/profile", label: "My Profile", icon: "User" },
];

export const NAV_ADMIN = [
  { to: "/admin/dashboard", label: "Dashboard", icon: "LayoutDashboard" },
  { to: "/admin/users", label: "User Management", icon: "Users" },
  { to: "/admin/farmers", label: "Farmer Approval", icon: "BadgeCheck", badge: 3 },
  { to: "/admin/moderation", label: "Product Moderation", icon: "ShieldCheck", badge: 3 },
  { to: "/admin/orders", label: "Order Management", icon: "ShoppingBag" },
  { to: "/admin/reports", label: "Reports", icon: "BarChart3" },
  { to: "/admin/settings", label: "System Settings", icon: "Settings" },
];
